#!/bin/bash

VLCOMMON=/usr/share/vlizedlab/scripts/common
if [ -f $VLCOMMON ]; then source $VLCOMMON ; else exit 1; fi

echo -n "Pinging active remote machines. Please wait "  >&2

for ff in `grep -v '#' $MYSTUDENTLIST`; do
   if ping -c 1 -W 1 $ff > /dev/null ; then 
	FULLIPLIST="$FULLIPLIST $ff"
        echo -n "*" >&2
   else
        echo -n "." >&2
   fi
done

echo "" >&2

if [ "$FULLIPLIST" = "" ]; then
    echo "No machines configured for remote maintenance" >&2
    exit 1
fi

RADIOLIST="none . on"
for ip in $FULLIPLIST ; do
        RADIOLIST="$RADIOLIST $ip . off"
done

IPCHOICE=`dialog --cr-wrap \
                --backtitle "$VLTITLE"\
          --radiolist 'Choose machine to view with vnc:' 0 0 0 \
		$RADIOLIST \
                   3>&1 1>&2 2>&3 | sed '1,$ s/"//g'`

echo $IPCHOICE

