#!/bin/bash

VLCOMMON=/usr/share/vlizedlab/scripts/common
if [ -f $VLCOMMON ]; then source $VLCOMMON ; else exit 1; fi

FULLIPLIST=""

echo -n "Pinging active remote machines. Please wait "  >&2

for ff in `grep -v '#' $MYSTUDENTLIST`; do
   if ping -c 1 -W 1 $ff > /dev/null ; then 
	FULLIPLIST="$FULLIPLIST $ff"
        echo -n "*" >&2
   else
        echo -n "." >&2
   fi
done

echo "" >&2

if [ "$FULLIPLIST" = "" ]; then
    echo "No machines configured for remote maintenance" >&2
    exit 1
fi

CHECKLIST="all . off"
for ip in $FULLIPLIST ; do
        CHECKLIST="$CHECKLIST $ip . off"
done

IPLIST=`dialog --cr-wrap \
                --backtitle "$VLTITLE"\
          --checklist 'Remote Maintenance - Please choose what to do:' 0 0 0 \
		$CHECKLIST \
                   3>&1 1>&2 2>&3 | sed '1,$ s/"//g'`

if [ "`echo $IPLIST | awk '{print $1}'`" = "all" ]; then
        IPLIST=$FULLIPLIST
fi

echo $IPLIST

