#!/bin/bash
# normally started as user Student within X

VLCOMMON=/usr/share/vlizedlab/scripts/common
if [ -f $VLCOMMON ]; then source $VLCOMMON ; else exit 1; fi

TITLE="VlizedlabClient (c)the-M `_version` - `hostname`"
sleep 1

#_startvm () {
#     if [ -d $VMHOME/$1 ]; then
#        echo "Starting  Virtual Machine vms/$1"
#
#	VMFILE="`find $VMHOME/$1 -name '*.vmx' -print | head -1`"
#	vmplayer "$VMFILE" 2>&1 > /dev/null &
#	echo "starting ..."
#
#	sleep 5
#
#	echo "Started."
#     fi
#}

DOEXIT=no

while [ "$DOEXIT" != yes ]; do

	MENU=""
	NR=0
	XC=/vm/vb/autostart
	MDIR=/vm/vb
	
	   MNAME=`basename $XC`
	   MDIR=`dirname $XC`
	   MTOOL=`basename $MDIR`
	   MENU="$MENU $NR ${MNAME}"

	MENU="$MENU x _xterm  t _exit_X"

	choice=`dialog --cr-wrap \
                 --backtitle "$TITLE" \
        	   --nocancel \
         	   --default-item 0\
          	   --timeout 1 \
	          --menu 'What do you want to do? a' 0 0 0 $MENU 3>&1 1>&2 2>&3`

	clear

	case $choice in 
	   x) 
             xterm -e bash -c "echo 'Logging in as user >student<; Please provide password.'; sudo /bin/login student" &
             ;;
	   t) 
             DOEXIT=yes
             ;;
	   *)
	     VM="" 
	     NR=0
		   MNAME=`basename $XC`
		   MDIR=`dirname $XC`
		   MTOOL=`basename $MDIR`
		   MENU="$MENU $NR ${MNAME}"
	     
	       vlstartvbmachine $MTOOL/$MNAME

	     echo "waiting..."
	     sleep 5
	     ;;
	esac
done

#for ff in `ps augx | grep vmware | grep /space/vms | awk '{print $1}'` ; do
#    kill $ff
#done


